version: '3'

volumes:
  daro-vol:

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      # POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - daro-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: dijidaro-app:daro-app-v1
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/usr/src/app

  # redis:
  #   image: redis:alpine
  #   ports:
  #     - 6379:6379
